#!/usr/bin/python
# -*- coding: utf-8 -*-

# execution.py

from __future__ import print_function

from abc import ABCMeta, abstractmethod
import datetime

try:
    import Queue as queue
except ImportError:
    import queue

from backtesting.event import *


class ExecutionHandler(object):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market. 

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This allows
    strategies to be backtested in a very similar manner to the
    live trading engine.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an Order event and executes it, producing
        a Fill event that gets placed onto the Events queue.

        Parameters:
        event - Contains an Event object with order information.
        """
        raise NotImplementedError("Should implement execute_order()")


class SimulatedExecutionHandler(ExecutionHandler):
    """
    The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    This allows a straightforward "first go" test of any strategy,
    before implementation with a more sophisticated execution
    handler.
    """

    def __init__(self, events, commission, exchange):
        """
        Initialises the handler, setting the event queues
        up internally.

        Parameters:
        events - The Queue of Event objects.
        """
        self.events = events
        self.commission = commission
        self.exchange = exchange

    def execute_order(self, event):
        """
        Simply converts Order objects into Fill objects naively,
        i.e. without any latency, slippage or fill ratio problems.

        Parameters:
        event - Contains an Event object with order information.
        """
        if event.type_ == EVENT_ORDER:
            # 理论上如果是期货要先卖出再买入.
            fill_event = EventFill(
                timeindex=datetime.datetime.utcnow(), symbol=event.symbol,
                exchange=self.exchange, quantity=event.quantity, direction=event.direction, commission=self.commission,
                fill_cost=None
            )
            self.events.put(fill_event)

class realExecutionHandler(ExecutionHandler):

    def __init__(self, events, commission, exchange):
        """
        Initialises the handler, setting the event queues
        up internally.

        Parameters:
        events - The Queue of Event objects.
        """
        self.events = events
        self.commission = commission
        self.exchange = exchange

    def execute_order(self, event):
        """
        Simply converts Order objects into Fill objects naively,
        i.e. without any latency, slippage or fill ratio problems.

        Parameters:
        event - Contains an Event object with order information.
        """
        if event.type_ == EVENT_ORDER:
            # 理论上如果是期货要先卖出再买入.
            fill_event = EventFill(
                timeindex=datetime.datetime.utcnow(), symbol=event.symbol,
                exchange=self.exchange, quantity=event.quantity, direction=event.direction, commission=self.commission,
                fill_cost=None
            )
            self.events.put(fill_event)