# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myquant_backtesting_py3.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1236, 845)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.lineEdit_symbol = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_symbol.setObjectName("lineEdit_symbol")
        self.gridLayout.addWidget(self.lineEdit_symbol, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_begindate = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_begindate.setObjectName("lineEdit_begindate")
        self.gridLayout.addWidget(self.lineEdit_begindate, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.line_Strategy = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_Strategy.setObjectName("line_Strategy")
        self.gridLayout.addWidget(self.line_Strategy, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.Hist_path = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.Hist_path.setObjectName("Hist_path")
        self.gridLayout.addWidget(self.Hist_path, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.lineEdit_Capital = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_Capital.setObjectName("lineEdit_Capital")
        self.gridLayout.addWidget(self.lineEdit_Capital, 3, 1, 1, 1)
        self.label_lever = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_lever.setObjectName("label_lever")
        self.gridLayout.addWidget(self.label_lever, 1, 3, 1, 1)
        self.lineEdit_lever = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_lever.setMaximumSize(QtCore.QSize(150, 150))
        self.lineEdit_lever.setObjectName("lineEdit_lever")
        self.gridLayout.addWidget(self.lineEdit_lever, 1, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 3, 1, 1)
        self.lineEdit_commission = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_commission.setMaximumSize(QtCore.QSize(150, 150))
        self.lineEdit_commission.setObjectName("lineEdit_commission")
        self.gridLayout.addWidget(self.lineEdit_commission, 2, 4, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_type.setCurrentText("")
        self.comboBox_type.setObjectName("comboBox_type")
        self.gridLayout.addWidget(self.comboBox_type, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_createpicture = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_createpicture.setObjectName("pushButton_createpicture")
        self.gridLayout_2.addWidget(self.pushButton_createpicture, 1, 0, 1, 1)
        self.pushButton_capital = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_capital.setObjectName("pushButton_capital")
        self.gridLayout_2.addWidget(self.pushButton_capital, 2, 0, 1, 1)
        self.pushButton_Backteston = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_Backteston.setObjectName("pushButton_Backteston")
        self.gridLayout_2.addWidget(self.pushButton_Backteston, 0, 0, 1, 1)
        self.pushButton_drawdown = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_drawdown.setObjectName("pushButton_drawdown")
        self.gridLayout_2.addWidget(self.pushButton_drawdown, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.dockWidget_2.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_type.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "蜡烛图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "资金曲线图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "回撤图"))
        self.label_6.setText(_translate("MainWindow", "例: [\'00001.SH\']"))
        self.lineEdit_symbol.setText(_translate("MainWindow", "[\'000001.SH\']"))
        self.label_3.setText(_translate("MainWindow", "回测开始日期"))
        self.lineEdit_begindate.setText(_translate("MainWindow", "19900101"))
        self.label_8.setText(_translate("MainWindow", "初始资金"))
        self.label_7.setText(_translate("MainWindow", "例: 19900101"))
        self.line_Strategy.setText(_translate("MainWindow", "MovingAverageCrossStrategy"))
        self.label.setText(_translate("MainWindow", "csv历史数据文件目录:"))
        self.label_5.setText(_translate("MainWindow", "例: ~/data"))
        self.Hist_path.setText(_translate("MainWindow", "~/data"))
        self.label_4.setText(_translate("MainWindow", "策略名称"))
        self.label_2.setText(_translate("MainWindow", "symbol_lsit"))
        self.label_9.setText(_translate("MainWindow", "类型"))
        self.lineEdit_Capital.setText(_translate("MainWindow", "10000"))
        self.label_lever.setText(_translate("MainWindow", "杠杆(元/单位价差)"))
        self.lineEdit_lever.setText(_translate("MainWindow", "10"))
        self.label_10.setText(_translate("MainWindow", "交易费元/手"))
        self.lineEdit_commission.setText(_translate("MainWindow", "3.5"))
        self.pushButton_createpicture.setText(_translate("MainWindow", "回测完成后点击生成回测图"))
        self.pushButton_capital.setText(_translate("MainWindow", "生成资金曲线图"))
        self.pushButton_Backteston.setText(_translate("MainWindow", "开始回测"))
        self.pushButton_drawdown.setText(_translate("MainWindow", "生成回撤图"))
        self.action.setText(_translate("MainWindow", "打开策略"))


