# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_myquant_py3.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1351, 946)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_currentinfo = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_currentinfo.setObjectName("tabWidget_currentinfo")
        self.CURRENT_INFO = QtWidgets.QWidget()
        self.CURRENT_INFO.setObjectName("CURRENT_INFO")
        self.tableWidget_DepthMarket = QtWidgets.QTableWidget(self.CURRENT_INFO)
        self.tableWidget_DepthMarket.setGeometry(QtCore.QRect(0, 40, 931, 501))
        self.tableWidget_DepthMarket.setMouseTracking(False)
        self.tableWidget_DepthMarket.setAutoScroll(True)
        self.tableWidget_DepthMarket.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_DepthMarket.setProperty("showDropIndicator", True)
        self.tableWidget_DepthMarket.setDragEnabled(False)
        self.tableWidget_DepthMarket.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget_DepthMarket.setShowGrid(True)
        self.tableWidget_DepthMarket.setObjectName("tableWidget_DepthMarket")
        self.tableWidget_DepthMarket.setColumnCount(10)
        self.tableWidget_DepthMarket.setRowCount(18)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(0, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(2, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(4, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(5, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(6, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(7, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(8, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(9, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(10, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(11, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(12, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(13, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(14, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(15, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(16, 9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_DepthMarket.setItem(17, 9, item)
        self.tableWidget_DepthMarket.horizontalHeader().setVisible(True)
        self.tableWidget_DepthMarket.verticalHeader().setVisible(True)
        self.tableWidget_DepthMarket.verticalHeader().setHighlightSections(True)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.CURRENT_INFO)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 292, 31))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_code = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.gridLayout_8.addWidget(self.lineEdit_code, 0, 1, 1, 1)
        self.label_contractt = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_contractt.setObjectName("label_contractt")
        self.gridLayout_8.addWidget(self.label_contractt, 0, 0, 1, 1)
        self.pushButton_qry = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_qry.setObjectName("pushButton_qry")
        self.gridLayout_8.addWidget(self.pushButton_qry, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.CURRENT_INFO)
        self.label_5.setGeometry(QtCore.QRect(430, 0, 201, 31))
        self.label_5.setObjectName("label_5")
        self.tabWidget_currentinfo.addTab(self.CURRENT_INFO, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_Instrument = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_Instrument.setGeometry(QtCore.QRect(0, 30, 931, 491))
        self.tableWidget_Instrument.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Instrument.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Instrument.setObjectName("tableWidget_Instrument")
        self.tableWidget_Instrument.setColumnCount(11)
        self.tableWidget_Instrument.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_Instrument.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_Instrument.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Instrument.setHorizontalHeaderItem(10, item)
        self.tableWidget_Instrument.horizontalHeader().setDefaultSectionSize(84)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(260, 0, 421, 35))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_searchInstrument = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_searchInstrument.setObjectName("lineEdit_searchInstrument")
        self.horizontalLayout_4.addWidget(self.lineEdit_searchInstrument)
        self.pushButton_searchInstruemt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_searchInstruemt.setObjectName("pushButton_searchInstruemt")
        self.horizontalLayout_4.addWidget(self.pushButton_searchInstruemt)
        self.pushButton_loadInstrument = QtWidgets.QPushButton(self.tab)
        self.pushButton_loadInstrument.setGeometry(QtCore.QRect(0, 0, 85, 31))
        self.pushButton_loadInstrument.setObjectName("pushButton_loadInstrument")
        self.tabWidget_currentinfo.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget_currentinfo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1351, 22))
        self.menubar.setObjectName("menubar")
        self.menuAlgorithm_Trading = QtWidgets.QMenu(self.menubar)
        self.menuAlgorithm_Trading.setObjectName("menuAlgorithm_Trading")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setMinimumSize(QtCore.QSize(345, 250))
        self.dockWidget_3.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BrokerID = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.BrokerID.setObjectName("BrokerID")
        self.gridLayout_2.addWidget(self.BrokerID, 2, 0, 1, 1)
        self.jiaoyidizhi = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.jiaoyidizhi.setObjectName("jiaoyidizhi")
        self.gridLayout_2.addWidget(self.jiaoyidizhi, 0, 0, 1, 1)
        self.zhanghao = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.zhanghao.setObjectName("zhanghao")
        self.gridLayout_2.addWidget(self.zhanghao, 3, 0, 1, 1)
        self.mima = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.mima.setObjectName("mima")
        self.gridLayout_2.addWidget(self.mima, 4, 0, 1, 1)
        self.USEREdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.USEREdit.setObjectName("USEREdit")
        self.gridLayout_2.addWidget(self.USEREdit, 3, 1, 1, 1)
        self.MDEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.MDEdit.setObjectName("MDEdit")
        self.gridLayout_2.addWidget(self.MDEdit, 1, 1, 1, 1)
        self.BIDEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.BIDEdit.setObjectName("BIDEdit")
        self.gridLayout_2.addWidget(self.BIDEdit, 2, 1, 1, 1)
        self.PWEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.PWEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PWEdit.setObjectName("PWEdit")
        self.gridLayout_2.addWidget(self.PWEdit, 4, 1, 1, 1)
        self.TDEdit = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.TDEdit.setObjectName("TDEdit")
        self.gridLayout_2.addWidget(self.TDEdit, 0, 1, 1, 1)
        self.hangqingdizhi = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.hangqingdizhi.setObjectName("hangqingdizhi")
        self.gridLayout_2.addWidget(self.hangqingdizhi, 1, 0, 1, 1)
        self.checkBox_saveLogin = QtWidgets.QCheckBox(self.dockWidgetContents_3)
        self.checkBox_saveLogin.setObjectName("checkBox_saveLogin")
        self.gridLayout_2.addWidget(self.checkBox_saveLogin, 5, 0, 1, 1)
        self.pushButton_login = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout_2.addWidget(self.pushButton_login, 5, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.dockWidget_5 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_5.setMinimumSize(QtCore.QSize(397, 308))
        self.dockWidget_5.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_5.setObjectName("dockWidget_5")
        self.dockWidgetContents_5 = QtWidgets.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_contractt_2 = QtWidgets.QLabel(self.dockWidgetContents_5)
        self.label_contractt_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_contractt_2.setObjectName("label_contractt_2")
        self.horizontalLayout_2.addWidget(self.label_contractt_2)
        self.label_order_code = QtWidgets.QLineEdit(self.dockWidgetContents_5)
        self.label_order_code.setMinimumSize(QtCore.QSize(125, 0))
        self.label_order_code.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_order_code.setObjectName("label_order_code")
        self.horizontalLayout_2.addWidget(self.label_order_code)
        self.label_volume = QtWidgets.QLabel(self.dockWidgetContents_5)
        self.label_volume.setObjectName("label_volume")
        self.horizontalLayout_2.addWidget(self.label_volume)
        self.lineEdit_volume = QtWidgets.QLineEdit(self.dockWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_volume.sizePolicy().hasHeightForWidth())
        self.lineEdit_volume.setSizePolicy(sizePolicy)
        self.lineEdit_volume.setMinimumSize(QtCore.QSize(110, 0))
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.horizontalLayout_2.addWidget(self.lineEdit_volume)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_5)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 415, 38))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.OFFSET_OPEN = QtWidgets.QRadioButton(self.layoutWidget)
        self.OFFSET_OPEN.setObjectName("OFFSET_OPEN")
        self.horizontalLayout_3.addWidget(self.OFFSET_OPEN)
        self.OFFSET_CLOSEY = QtWidgets.QRadioButton(self.layoutWidget)
        self.OFFSET_CLOSEY.setObjectName("OFFSET_CLOSEY")
        self.horizontalLayout_3.addWidget(self.OFFSET_CLOSEY)
        self.OFFSET_CLOSETODAY = QtWidgets.QRadioButton(self.layoutWidget)
        self.OFFSET_CLOSETODAY.setObjectName("OFFSET_CLOSETODAY")
        self.horizontalLayout_3.addWidget(self.OFFSET_CLOSETODAY)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents_5)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 415, 38))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.Direction_BUY = QtWidgets.QRadioButton(self.layoutWidget1)
        self.Direction_BUY.setObjectName("Direction_BUY")
        self.horizontalLayout.addWidget(self.Direction_BUY)
        self.Direction_SELL = QtWidgets.QRadioButton(self.layoutWidget1)
        self.Direction_SELL.setObjectName("Direction_SELL")
        self.horizontalLayout.addWidget(self.Direction_SELL)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents_5)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 10, 415, 37))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_limitprice = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_limitprice.setObjectName("radioButton_limitprice")
        self.horizontalLayout_6.addWidget(self.radioButton_limitprice)
        self.lineEdit_limitprice = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_limitprice.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_limitprice.setObjectName("lineEdit_limitprice")
        self.horizontalLayout_6.addWidget(self.lineEdit_limitprice)
        self.radioButton_SJ = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_SJ.setObjectName("radioButton_SJ")
        self.horizontalLayout_6.addWidget(self.radioButton_SJ)
        self.label_lastprice = QtWidgets.QLabel(self.layoutWidget2)
        self.label_lastprice.setMinimumSize(QtCore.QSize(120, 24))
        self.label_lastprice.setText("")
        self.label_lastprice.setObjectName("label_lastprice")
        self.horizontalLayout_6.addWidget(self.label_lastprice)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_Orderin = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_Orderin.setEnabled(True)
        self.pushButton_Orderin.setObjectName("pushButton_Orderin")
        self.horizontalLayout_5.addWidget(self.pushButton_Orderin)
        self.pushButton_OrderOut = QtWidgets.QPushButton(self.dockWidgetContents_5)
        self.pushButton_OrderOut.setObjectName("pushButton_OrderOut")
        self.horizontalLayout_5.addWidget(self.pushButton_OrderOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.dockWidget_5.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_5)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(591, 331))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tabWidget_Mission = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget_Mission.setObjectName("tabWidget_Mission")
        self.tab_BID = QtWidgets.QWidget()
        self.tab_BID.setObjectName("tab_BID")
        self.tableWidget_onrtnorder = QtWidgets.QTableWidget(self.tab_BID)
        self.tableWidget_onrtnorder.setGeometry(QtCore.QRect(0, 0, 571, 291))
        self.tableWidget_onrtnorder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_onrtnorder.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget_onrtnorder.setObjectName("tableWidget_onrtnorder")
        self.tableWidget_onrtnorder.setColumnCount(0)
        self.tableWidget_onrtnorder.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_onrtnorder.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget_onrtnorder.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtnorder.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_onrtnorder.setVerticalHeaderItem(9, item)
        self.tableWidget_onrtnorder.verticalHeader().setDefaultSectionSize(22)
        self.pushButton_OrderReq = QtWidgets.QPushButton(self.tab_BID)
        self.pushButton_OrderReq.setGeometry(QtCore.QRect(0, 220, 61, 20))
        self.pushButton_OrderReq.setObjectName("pushButton_OrderReq")
        self.pushButton_onrtndel = QtWidgets.QPushButton(self.tab_BID)
        self.pushButton_onrtndel.setGeometry(QtCore.QRect(0, 240, 61, 21))
        self.pushButton_onrtndel.setObjectName("pushButton_onrtndel")
        self.tabWidget_Mission.addTab(self.tab_BID, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_onrtntrade = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_onrtntrade.setGeometry(QtCore.QRect(0, 0, 571, 261))
        self.tableWidget_onrtntrade.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_onrtntrade.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget_onrtntrade.setObjectName("tableWidget_onrtntrade")
        self.tableWidget_onrtntrade.setColumnCount(0)
        self.tableWidget_onrtntrade.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_onrtntrade.setVerticalHeaderItem(7, item)
        self.pushButton_TradeReq = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_TradeReq.setGeometry(QtCore.QRect(0, 230, 61, 31))
        self.pushButton_TradeReq.setObjectName("pushButton_TradeReq")
        self.tabWidget_Mission.addTab(self.tab_4, "")
        self.gridLayout_9.addWidget(self.tabWidget_Mission, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(707, 331))
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tabWidget_INFO = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget_INFO.setObjectName("tabWidget_INFO")
        self.tab_HOLD = QtWidgets.QWidget()
        self.tab_HOLD.setObjectName("tab_HOLD")
        self.tableWidget_position = QtWidgets.QTableWidget(self.tab_HOLD)
        self.tableWidget_position.setGeometry(QtCore.QRect(0, 0, 341, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_position.setFont(font)
        self.tableWidget_position.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_position.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget_position.setObjectName("tableWidget_position")
        self.tableWidget_position.setColumnCount(5)
        self.tableWidget_position.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_position.setItem(9, 4, item)
        self.tableWidget_position.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_position.verticalHeader().setMinimumSectionSize(18)
        self.tabWidget_INFO.addTab(self.tab_HOLD, "")
        self.gridLayout_10.addWidget(self.tabWidget_INFO, 0, 0, 1, 1)
        self.tabWidget_INFO_2 = QtWidgets.QTabWidget(self.dockWidgetContents_2)
        self.tabWidget_INFO_2.setObjectName("tabWidget_INFO_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_Account = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_Account.setGeometry(QtCore.QRect(0, 0, 151, 161))
        self.tableWidget_Account.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_Account.setObjectName("tableWidget_Account")
        self.tableWidget_Account.setColumnCount(1)
        self.tableWidget_Account.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Account.setHorizontalHeaderItem(0, item)
        self.tabWidget_INFO_2.addTab(self.tab_5, "")
        self.gridLayout_10.addWidget(self.tabWidget_INFO_2, 0, 1, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_2)
        self.action_Backtesting = QtWidgets.QAction(MainWindow)
        self.action_Backtesting.setObjectName("action_Backtesting")
        self.action_RealTrading = QtWidgets.QAction(MainWindow)
        self.action_RealTrading.setObjectName("action_RealTrading")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.menuAlgorithm_Trading.addAction(self.action_Backtesting)
        self.menuAlgorithm_Trading.addAction(self.action_RealTrading)
        self.menuAbout.addAction(self.actionInfo)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionContact)
        self.menubar.addAction(self.menuAlgorithm_Trading.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_currentinfo.setCurrentIndex(0)
        self.tabWidget_Mission.setCurrentIndex(0)
        self.tabWidget_INFO.setCurrentIndex(0)
        self.tabWidget_INFO_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget_DepthMarket.setWhatsThis(_translate("MainWindow", "交易地址可以从http://www.simnow.com.cn/product.action获取"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "合约代码"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "最新价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "昨收盘价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "昨持仓量"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "open"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "high"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "low"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "成交金额"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "持仓量"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "卖一量"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "卖一价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "买一价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "买一量"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "涨停价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "跌停价"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "交易所"))
        item = self.tableWidget_DepthMarket.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "更新时间"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget_DepthMarket.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        __sortingEnabled = self.tableWidget_DepthMarket.isSortingEnabled()
        self.tableWidget_DepthMarket.setSortingEnabled(False)
        item = self.tableWidget_DepthMarket.item(0, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 5)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 6)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 7)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 8)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_DepthMarket.item(0, 9)
        item.setText(_translate("MainWindow", "_"))
        self.tableWidget_DepthMarket.setSortingEnabled(__sortingEnabled)
        self.lineEdit_code.setText(_translate("MainWindow", "rb1910"))
        self.label_contractt.setText(_translate("MainWindow", "合约代码"))
        self.pushButton_qry.setText(_translate("MainWindow", "查询"))
        self.label_5.setText(_translate("MainWindow", "tips:单击对应合约代码加入下单板"))
        self.tabWidget_currentinfo.setTabText(self.tabWidget_currentinfo.indexOf(self.CURRENT_INFO), _translate("MainWindow", "实时行情"))
        self.tableWidget_Instrument.setSortingEnabled(True)
        item = self.tableWidget_Instrument.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "合约代码"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "交易所"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "限价最小下单量"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "市价最小下单量"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "最小变动价位"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "到期日"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "空头保证金率"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "多头保证金率"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "合约数量乘数"))
        item = self.tableWidget_Instrument.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "交割日"))
        self.pushButton_searchInstruemt.setText(_translate("MainWindow", "查询合约"))
        self.pushButton_loadInstrument.setText(_translate("MainWindow", "载入合约"))
        self.tabWidget_currentinfo.setTabText(self.tabWidget_currentinfo.indexOf(self.tab), _translate("MainWindow", "所有合约列表"))
        self.menuAlgorithm_Trading.setTitle(_translate("MainWindow", "Algorithm Trading"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.BrokerID.setText(_translate("MainWindow", "BrokerID"))
        self.jiaoyidizhi.setText(_translate("MainWindow", "交易地址"))
        self.zhanghao.setText(_translate("MainWindow", "账号"))
        self.mima.setText(_translate("MainWindow", "密码"))
        self.USEREdit.setText(_translate("MainWindow", "092122"))
        self.MDEdit.setText(_translate("MainWindow", "tcp://218.202.237.33:10012"))
        self.BIDEdit.setText(_translate("MainWindow", "9999"))
        self.TDEdit.setWhatsThis(_translate("MainWindow", "交易行情,可以从http://www.simnow.com.cn/product.action获取"))
        self.TDEdit.setText(_translate("MainWindow", "tcp://218.202.237.33:10002"))
        self.hangqingdizhi.setText(_translate("MainWindow", "行情地址"))
        self.checkBox_saveLogin.setText(_translate("MainWindow", "保存登录信息"))
        self.pushButton_login.setText(_translate("MainWindow", "登录Login"))
        self.label_contractt_2.setText(_translate("MainWindow", "合约代码:"))
        self.label_volume.setText(_translate("MainWindow", "下单数量"))
        self.lineEdit_volume.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "开平:"))
        self.OFFSET_OPEN.setText(_translate("MainWindow", "开仓"))
        self.OFFSET_CLOSEY.setText(_translate("MainWindow", "平昨"))
        self.OFFSET_CLOSETODAY.setText(_translate("MainWindow", "平今"))
        self.label_6.setText(_translate("MainWindow", "方向:"))
        self.Direction_BUY.setText(_translate("MainWindow", "买"))
        self.Direction_SELL.setText(_translate("MainWindow", "卖"))
        self.radioButton_limitprice.setText(_translate("MainWindow", "限价"))
        self.radioButton_SJ.setText(_translate("MainWindow", "市价"))
        self.pushButton_Orderin.setText(_translate("MainWindow", "发单"))
        self.pushButton_OrderOut.setText(_translate("MainWindow", "撤单"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "合约代码"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "开平/买卖"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "报单价格"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "报单数量"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "已成交数"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "委托时间"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "状态"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "交易所代码"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "FrontID"))
        item = self.tableWidget_onrtnorder.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "SessionID"))
        self.pushButton_OrderReq.setText(_translate("MainWindow", "查询委托"))
        self.pushButton_onrtndel.setText(_translate("MainWindow", "清空列表"))
        self.tabWidget_Mission.setTabText(self.tabWidget_Mission.indexOf(self.tab_BID), _translate("MainWindow", "委托"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "合约代码"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "开平"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "买卖"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "成交价格"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "成交数量"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "成交时间"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "成交编号"))
        item = self.tableWidget_onrtntrade.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "报单编号"))
        self.pushButton_TradeReq.setText(_translate("MainWindow", "查询成交"))
        self.tabWidget_Mission.setTabText(self.tabWidget_Mission.indexOf(self.tab_4), _translate("MainWindow", "成交"))
        item = self.tableWidget_position.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "成交时间"))
        item = self.tableWidget_position.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "合约代码"))
        item = self.tableWidget_position.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "方向"))
        item = self.tableWidget_position.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "昨日持仓"))
        item = self.tableWidget_position.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "今日持仓"))
        item = self.tableWidget_position.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "持仓成本"))
        item = self.tableWidget_position.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "占用保证金"))
        item = self.tableWidget_position.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "开仓成本"))
        item = self.tableWidget_position.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "持仓盈亏"))
        item = self.tableWidget_position.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "平仓盈亏"))
        item = self.tableWidget_position.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_position.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_position.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_position.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_position.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        __sortingEnabled = self.tableWidget_position.isSortingEnabled()
        self.tableWidget_position.setSortingEnabled(False)
        item = self.tableWidget_position.item(0, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(0, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(0, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(0, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(0, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(1, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(1, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(1, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(1, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(1, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(2, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(2, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(2, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(2, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(2, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(3, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(3, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(3, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(3, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(3, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(4, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(4, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(4, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(4, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(4, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(5, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(5, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(5, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(5, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(5, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(6, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(6, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(6, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(6, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(6, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(7, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(7, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(7, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(7, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(7, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(8, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(8, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(8, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(8, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(8, 4)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(9, 0)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(9, 1)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(9, 2)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(9, 3)
        item.setText(_translate("MainWindow", "_"))
        item = self.tableWidget_position.item(9, 4)
        item.setText(_translate("MainWindow", "_"))
        self.tableWidget_position.setSortingEnabled(__sortingEnabled)
        self.tabWidget_INFO.setTabText(self.tabWidget_INFO.indexOf(self.tab_HOLD), _translate("MainWindow", "持仓"))
        item = self.tableWidget_Account.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "账户编号"))
        item = self.tableWidget_Account.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "昨日净值"))
        item = self.tableWidget_Account.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "可用"))
        item = self.tableWidget_Account.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "手续费"))
        item = self.tableWidget_Account.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "保证金"))
        item = self.tableWidget_Account.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        self.tabWidget_INFO_2.setTabText(self.tabWidget_INFO_2.indexOf(self.tab_5), _translate("MainWindow", "账户资金"))
        self.action_Backtesting.setText(_translate("MainWindow", "历史回测"))
        self.action_RealTrading.setText(_translate("MainWindow", "策略实盘"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))


