from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_Real_Trade(QMainWindow):

    def __init__(self):
        super(Ui_Real_Trade, self).__init__()


    def setupUi(self, Real_Trade):
        Real_Trade.setObjectName("Real_Trade")
        Real_Trade.resize(740, 606)
        self.centralwidget = QtWidgets.QWidget(Real_Trade)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 25)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 6, 0, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 9, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 14, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 10, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 12, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 13, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 8, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 0, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 1, 1, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        Real_Trade.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(Real_Trade)
        self.dockWidget.setMinimumSize(QtCore.QSize(350, 300))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_30 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 0, 1, 1)
        self.pushButton_ONREALTRADE = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_ONREALTRADE.setObjectName("pushButton_ONREALTRADE")
        self.gridLayout_3.addWidget(self.pushButton_ONREALTRADE, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.comboBox_style = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox_style.setObjectName("comboBox_style")
        self.gridLayout_3.addWidget(self.comboBox_style, 2, 1, 1, 1)
        self.lineEdit_symbol = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_symbol.setObjectName("lineEdit_symbol")
        self.gridLayout_3.addWidget(self.lineEdit_symbol, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_volume = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_volume.setObjectName("lineEdit_volume")
        self.gridLayout_8.addWidget(self.lineEdit_volume, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 3, 1, 1, 1)
        self.lineEdit_strategy = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit_strategy.setObjectName("lineEdit_strategy")
        self.gridLayout_3.addWidget(self.lineEdit_strategy, 1, 1, 1, 1)
        self.pushButton_Initialparameter = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_Initialparameter.setObjectName("pushButton_Initialparameter")
        self.gridLayout_3.addWidget(self.pushButton_Initialparameter, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_frommysql = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_frommysql.setObjectName("pushButton_frommysql")
        self.horizontalLayout.addWidget(self.pushButton_frommysql)
        self.pushButton_fromcsv = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_fromcsv.setObjectName("pushButton_fromcsv")
        self.horizontalLayout.addWidget(self.pushButton_fromcsv)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.pushButton_Initial = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_Initial.setObjectName("pushButton_Initial")
        self.gridLayout_3.addWidget(self.pushButton_Initial, 6, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        Real_Trade.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_2 = QtWidgets.QDockWidget(Real_Trade)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(323, 300))
        self.dockWidget_2.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 6, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_10.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 7, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_10, 1, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.dockWidgetContents_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_6.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        Real_Trade.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_2)

        self.retranslateUi(Real_Trade)
        QtCore.QMetaObject.connectSlotsByName(Real_Trade)

    def retranslateUi(self, Real_Trade):
        _translate = QtCore.QCoreApplication.translate
        Real_Trade.setWindowTitle(_translate("Real_Trade", "Real_Trade"))
        self.label_7.setText(_translate("Real_Trade", "在险资产"))
        self.label_6.setText(_translate("Real_Trade", "总资产"))
        self.label_4.setText(_translate("Real_Trade", "策略当前收益"))
        self.label_16.setText(_translate("Real_Trade", "TextLabel"))
        self.label_21.setText(_translate("Real_Trade", "TextLabel"))
        self.label_17.setText(_translate("Real_Trade", "TextLabel"))
        self.label_19.setText(_translate("Real_Trade", "TextLabel"))
        self.label_5.setText(_translate("Real_Trade", "交易次数"))
        self.label_24.setText(_translate("Real_Trade", "TextLabel"))
        self.label_20.setText(_translate("Real_Trade", "TextLabel"))
        self.label_8.setText(_translate("Real_Trade", "交易正确率"))
        self.label_22.setText(_translate("Real_Trade", "TextLabel"))
        self.label_23.setText(_translate("Real_Trade", "TextLabel"))
        self.label_18.setText(_translate("Real_Trade", "TextLabel"))
        self.label_25.setText(_translate("Real_Trade", "总收益"))
        self.label_30.setText(_translate("Real_Trade", "开始策略"))
        self.label_14.setText(_translate("Real_Trade", "策略初始化"))
        self.pushButton_ONREALTRADE.setText(_translate("Real_Trade", "策略启动"))
        self.label_3.setText(_translate("Real_Trade", "策略名称"))
        self.label_9.setText(_translate("Real_Trade", "每次交易(手)"))
        self.lineEdit_symbol.setText(_translate("Real_Trade", "rb1910"))
        self.label_2.setText(_translate("Real_Trade", "symbol"))
        self.label.setText(_translate("Real_Trade", "类型"))
        self.lineEdit_volume.setText(_translate("Real_Trade", "1"))
        self.lineEdit_strategy.setText(_translate("Real_Trade", "MovingAverageCrossStrategy"))
        self.pushButton_Initialparameter.setText(_translate("Real_Trade", "载入初始参数"))
        self.pushButton_frommysql.setText(_translate("Real_Trade", "从mysql数据库载入"))
        self.pushButton_fromcsv.setText(_translate("Real_Trade", "从csv文件载入"))
        self.pushButton_Initial.setText(_translate("Real_Trade", "策略初始化"))
        self.label_13.setText(_translate("Real_Trade", "TextLabel"))
        self.label_26.setText(_translate("Real_Trade", "TextLabel"))
        self.label_11.setText(_translate("Real_Trade", "止损(%)"))
        self.label_12.setText(_translate("Real_Trade", "单笔损失上限(元)"))
        self.label_28.setText(_translate("Real_Trade", "TextLabel"))
        self.label_27.setText(_translate("Real_Trade", "TextLabel"))
        self.label_29.setText(_translate("Real_Trade", "TextLabel"))
        self.label_10.setText(_translate("Real_Trade", "风险控制"))
        self.label_15.setText(_translate("Real_Trade", "模式"))





if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    ui = Ui_Real_Trade()
    ui.setupUi(ui)
    ui.show()
    sys.exit(app.exec_())